"""Kullanıcı favorileri ilişkisi ekle

Revision ID: 0e208beccb61
Revises: 21eae6aeac62
Create Date: 2025-08-31 22:33:59.125530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e208beccb61'
down_revision = '21eae6aeac62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kullanici_favorileri',
    sa.Column('kullanici_id', sa.Integer(), nullable=False),
    sa.Column('urun_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['kullanici_id'], ['kullanici.id'], ),
    sa.ForeignKeyConstraint(['urun_id'], ['urun.id'], ),
    sa.PrimaryKeyConstraint('kullanici_id', 'urun_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kullanici_favorileri')
    # ### end Alembic commands ###
