"""Sepete miktar ekle ilişkilendirme tablosu

Revision ID: 21eae6aeac62
Revises: afe6743a1aac
Create Date: 2025-08-31 14:42:28.145473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21eae6aeac62'
down_revision = 'afe6743a1aac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('siparis_urunleri', schema=None) as batch_op:
        batch_op.alter_column('adet',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('siparis_urunleri', schema=None) as batch_op:
        batch_op.alter_column('adet',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
