"""Replace is_admin boolean with role string

Revision ID: 469ec4880f5c
Revises: 934cc50b45b8
Create Date: 2025-09-16 14:44:34.362816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '469ec4880f5c'
down_revision = '934cc50b45b8'
branch_labels = None
depends_on = None


# YENİ, DÜZELTİLMİŞ HALİ
def upgrade():
    # ### commands auto generated by Alembic - adjusted by developer ###
    with op.batch_alter_table('kullanici', schema=None) as batch_op:
        # 1. Adım: Yeni 'role' sütununu GEÇİCİ olarak boş olabilir (nullable=True) şekilde ekle.
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=True))

    # 2. Adım: Mevcut TÜM kullanıcıların yeni 'role' sütununu 'user' olarak doldur.
    op.execute("UPDATE kullanici SET role = 'user' WHERE role IS NULL")

    with op.batch_alter_table('kullanici', schema=None) as batch_op:
        # 3. Adım: Artık tüm satırlar dolu olduğuna göre, sütunu tekrar boş olamaz (nullable=False) yap.
        batch_op.alter_column('role', nullable=False)

        # 4. Adım: Eski 'is_admin' sütununu kaldır.
        batch_op.drop_column('is_admin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kullanici', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_column('role')

    # ### end Alembic commands ###
