"""kullanıcılar kayıt yaparken ad ve soyad bilgisini de al

Revision ID: 934cc50b45b8
Revises: ed9a010bb448
Create Date: 2025-09-07 17:42:03.452279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '934cc50b45b8'
down_revision = 'ed9a010bb448'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kullanici', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ad', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('soyad', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kullanici', schema=None) as batch_op:
        batch_op.drop_column('soyad')
        batch_op.drop_column('ad')

    # ### end Alembic commands ###
