"""Initial migration

Revision ID: c1567732ed82
Revises: 
Create Date: 2025-09-23 21:08:17.629908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1567732ed82'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kullanici',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('sifre_hash', sa.String(length=256), nullable=False),
    sa.Column('olusturulma_tarihi', sa.DateTime(), nullable=True),
    sa.Column('ad', sa.String(length=50), nullable=True),
    sa.Column('soyad', sa.String(length=50), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('urun',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(length=100), nullable=False),
    sa.Column('aciklama', sa.Text(), nullable=False),
    sa.Column('fiyat', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('stok_miktari', sa.Integer(), nullable=False),
    sa.Column('resim_url', sa.String(length=255), nullable=True),
    sa.Column('olusturulma_tarihi', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kullanici_favorileri',
    sa.Column('kullanici_id', sa.Integer(), nullable=False),
    sa.Column('urun_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['kullanici_id'], ['kullanici.id'], ),
    sa.ForeignKeyConstraint(['urun_id'], ['urun.id'], ),
    sa.PrimaryKeyConstraint('kullanici_id', 'urun_id')
    )
    op.create_table('siparis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kullanici_id', sa.Integer(), nullable=False),
    sa.Column('toplam_fiyat', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('durum', sa.String(length=50), nullable=False),
    sa.Column('olusturulma_tarihi', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['kullanici_id'], ['kullanici.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('siparis_urunleri',
    sa.Column('siparis_id', sa.Integer(), nullable=False),
    sa.Column('urun_id', sa.Integer(), nullable=False),
    sa.Column('adet', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['siparis_id'], ['siparis.id'], ),
    sa.ForeignKeyConstraint(['urun_id'], ['urun.id'], ),
    sa.PrimaryKeyConstraint('siparis_id', 'urun_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('siparis_urunleri')
    op.drop_table('siparis')
    op.drop_table('kullanici_favorileri')
    op.drop_table('urun')
    op.drop_table('kullanici')
    # ### end Alembic commands ###
