"""Kullanıcı modeline is_admin alanı ekle

Revision ID: ed9a010bb448
Revises: 0e208beccb61
Create Date: 2025-09-06 18:21:42.910310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed9a010bb448'
down_revision = '0e208beccb61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kullanici', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kullanici', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
